title: CaptainShare
author:
  name: Appyfriends
  email: 'etienne.valette@gmail.com'
metadata:
    description: 'A curated directory of sharing economy resources to make & save money'
taxonomies: [region]
