title: CaptainShare
author:
  name: Appyfriends
  email: 'etienne.valette@gmail.com'
metadata:
    description: 'A curated directory of sharing economy resources to make & save money'
taxonomies: [region]
owner:
    facebook: CaptainShare
    twitter: CaptainShare
    google_plus: https://plus.google.com/113591471491719021812
